# Generated by Django 2.1.4 on 2019-01-06 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animes', '0004_title_dirpath'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtitle',
            name='path',
            field=models.FilePathField(null=True),
        ),
    ]
