# Generated by Django 2.1.2 on 2019-01-02 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tid', models.CharField(max_length=4)),
                ('rno', models.IntegerField()),
                ('subtitle', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='subtitle',
            unique_together={('tid', 'rno')},
        ),
    ]
