# Generated by Django 2.1.2 on 2019-01-02 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animes', '0002_auto_20190102_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtitle',
            name='rno',
            field=models.CharField(max_length=3),
        ),
    ]
