# Generated by Django 2.1.2 on 2018-12-30 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pref',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tid', models.CharField(max_length=4)),
                ('title', models.CharField(max_length=100)),
                ('titleYomi', models.CharField(max_length=100)),
                ('titleEn', models.CharField(max_length=100)),
                ('cat', models.CharField(max_length=1)),
                ('firstYear', models.CharField(max_length=4)),
                ('firstMonth', models.CharField(max_length=2)),
                ('firstEndYear', models.CharField(max_length=4)),
                ('firstEndMonth', models.CharField(max_length=2)),
                ('lastUpdate', models.CharField(max_length=10)),
            ],
        ),
    ]
