# Generated by Django 2.1.2 on 2018-12-30 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_pref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pref',
            name='title',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='pref',
            name='titleEn',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='pref',
            name='titleYomi',
            field=models.CharField(max_length=1000),
        ),
    ]
