# Generated by Django 2.1.2 on 2018-12-31 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20181230_2344'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Anime',
        ),
        migrations.DeleteModel(
            name='Pref',
        ),
    ]
