# Generated by Django 2.1.2 on 2018-12-31 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movies', '0004_auto_20181231_2253'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseInfo',
            fields=[
                ('tid', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('firstYear', models.CharField(max_length=4)),
                ('firstMonth', models.CharField(max_length=2)),
                ('firstEndYear', models.CharField(max_length=4, null=True)),
                ('firstEndMonth', models.CharField(max_length=2, null=True)),
                ('comment', models.CharField(max_length=4000, null=True)),
            ],
        ),
    ]
