# Generated by Django 2.1.2 on 2019-01-01 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_baseinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cast',
            fields=[
                ('tid', models.CharField(max_length=4, unique=True)),
                ('rno', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('charaName', models.CharField(max_length=100)),
                ('actor', models.CharField(max_length=100)),
                ('baseInfo', models.ForeignKey(on_delete=True, to='movies.BaseInfo')),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('tid', models.CharField(max_length=4, unique=True)),
                ('rno', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('bunrui', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('lyrics', models.CharField(max_length=100)),
                ('composition', models.CharField(max_length=100)),
                ('arrangement', models.CharField(max_length=100)),
                ('song', models.CharField(max_length=100)),
                ('baseInfo', models.ForeignKey(on_delete=True, to='movies.BaseInfo')),
            ],
        ),
    ]
