# Generated by Django 2.1.2 on 2019-01-01 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_cast_song'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cast',
            name='rno',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cast',
            name='tid',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='song',
            name='rno',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='song',
            name='tid',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterUniqueTogether(
            name='cast',
            unique_together={('tid', 'rno')},
        ),
        migrations.AlterUniqueTogether(
            name='song',
            unique_together={('tid', 'rno')},
        ),
    ]
