# Generated by Django 2.1.2 on 2019-01-01 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_auto_20190101_1343'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cast',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='song',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='cast',
            name='actor',
        ),
        migrations.RemoveField(
            model_name='cast',
            name='baseInfo',
        ),
        migrations.RemoveField(
            model_name='cast',
            name='charaName',
        ),
        migrations.RemoveField(
            model_name='cast',
            name='tid',
        ),
        migrations.RemoveField(
            model_name='song',
            name='arrangement',
        ),
        migrations.RemoveField(
            model_name='song',
            name='baseInfo',
        ),
        migrations.RemoveField(
            model_name='song',
            name='bunrui',
        ),
        migrations.RemoveField(
            model_name='song',
            name='composition',
        ),
        migrations.RemoveField(
            model_name='song',
            name='lyrics',
        ),
        migrations.RemoveField(
            model_name='song',
            name='song',
        ),
        migrations.RemoveField(
            model_name='song',
            name='tid',
        ),
        migrations.RemoveField(
            model_name='song',
            name='title',
        ),
    ]
