# Generated by Django 2.1.2 on 2019-01-01 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_auto_20190101_1400'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cast',
            fields=[
                ('rno', models.AutoField(primary_key=True, serialize=False)),
                ('charaName', models.CharField(max_length=100)),
                ('actor', models.CharField(max_length=100)),
                ('tid', models.ForeignKey(on_delete=True, to='movies.BaseInfo')),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('rno', models.AutoField(primary_key=True, serialize=False)),
                ('bunrui', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('lyrics', models.CharField(max_length=100)),
                ('composition', models.CharField(max_length=100)),
                ('arrangement', models.CharField(max_length=100)),
                ('song', models.CharField(max_length=100)),
                ('tid', models.ForeignKey(on_delete=True, to='movies.BaseInfo')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='song',
            unique_together={('tid', 'rno')},
        ),
        migrations.AlterUniqueTogether(
            name='cast',
            unique_together={('tid', 'rno')},
        ),
    ]
