# Generated by Django 2.1.2 on 2019-01-01 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0010_auto_20190101_1401'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cast',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='cast',
            name='tid',
        ),
        migrations.AlterUniqueTogether(
            name='song',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='song',
            name='tid',
        ),
        migrations.DeleteModel(
            name='BaseInfo',
        ),
        migrations.DeleteModel(
            name='Cast',
        ),
        migrations.DeleteModel(
            name='Song',
        ),
    ]
